name: "Finetuned_RealESRGAN_x4plus_GameEngineData"
platform: "tensorrt_plan"
max_batch_size : 0
input [
  {
    name: "lr"
    data_type: TYPE_FP32
    dims: [ 1, 3, -1, -1 ]
  }
]
output [
  {
    name: "hr"
    data_type: TYPE_FP32
    dims: [ 1, 3, -1, -1 ]
  }
]
